- astrokat/observatory.py
- scripts/astrokat-observe.py
Retrieve MKAT reference point from katconf if katconf is available, else use a local constant.
Rework of package imports.
JIRA: MT-171
> MT-171 get mkat reference point from katconfig

- setup.py
This package needs a setup.py to install as it's currently breaking our integration builds.
I added a very simple one just to get going, please expand as needed.
Error in integration tests:
```
Directory u'/home/kat/svn/astrokat' is not installable. File 'setup.py' not found.
Exception information:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
status = self.run(options, args)
File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 312, in run
wheel_cache
File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 295, in populate_requirement_set
wheel_cache=wheel_cache):
File "/usr/local/lib/python2.7/dist-packages/pip/req/req_file.py", line 93, in parse_requirements
for req in …
```
> Fix integration test errors by adding setup.py

- setup.py
These additional packages are used in the live system but were not specified as dependencies.
I'm adding them as optional extras (can be installed using `pip install -e .[live]`). See [PEP508](https://www.python.org/dev/peps/pep-0508/) for more information.
> Add `katconf`, `katcorelib` as extra dependencies

- .gitignore
- astrokat/__init__.py
- astrokat/__main__.py
- astrokat/observe_main.py
- scripts/astrokat-cals.py
- scripts/astrokat-fitflux.py
- scripts/astrokat-lst.py
- scripts/catalogue2obsfile.py
- scripts/readconfig.py
- setup.py
- Add _katversion_ so that we can get version strings derived from the git version info.  This is required for CAM's automated branch creation tool.
- Install the useful scripts so that they are available on the path.
- Add some more details to setup.py.
Closes issue #14
> Add katversion support and install scripts

- astrokat/observe_main.py
Don't overwrite next_target when there are no targets with cadences
> correct indentation for next_target assignment in cadence evaluation

- astrokat/observe_main.py
- astrokat/utility.py
Add check to exit if obs_duration is zero
New output:
```
> astrokat-observe.py --yaml tagtest.yaml
2019-07-30 14:44:54Z - Setting up telescope for observation
2019-07-30 14:44:54Z - Running astrokat version - 0.0+unknown.201907301644
2019-07-30 14:44:54Z - Request: Switch noise-diode off at 1564497900.0
2019-07-30 14:44:54Z - Dry-run: Set all noise diodes with timestamp 1564497900.0 (Tue Jul 30 16:45:00 2019)
2019-07-30 14:44:54Z - Unexpected value: obs_duration: 0.0
2019-07-30 14:44:54Z - Returning telescope to startup state
2019-07-30 14:44:54Z - Request: Switch noise-diode off at 1564497900.0
2019-07-30 14:44:54Z - Dry-run: Set all noise diodes with timestamp 1564497900.0 (Tue Jul 30 16:45:00 2019)
```
> add check for obs_duration=0

- astrokat/observe_main.py
- astrokat/test/test_offline_observe.py
Remove hardcoded dictionary of calibrator tags
Updated with code that extract all unique cal tags and use those to display output to user, thus whatever is in the YAML is displayed, making the code independent of user defined tags
New output:
```
2019-07-30 07:03:41Z - Found 5 target(s): 0 from 0 catalogue(s), 0 from default catalogue and 37 as target string(s)
2019-07-30 07:03:41Z - BP calibrators are ['J0408-6545']
2019-07-30 07:03:41Z - DELAY calibrators are ['J0408-6545']
2019-07-30 07:03:41Z - FLUX calibrators are ['J0408-6545']
2019-07-30 07:03:41Z - GAIN calibrators are ['J0632+1022', 'J1150-0023']
2019-07-30 07:03:41Z - Observation targets are ['3C 175', '3C 274']
```
> Remove hard coded cal tags

- Jenkinsfile
- pyproject.toml
- setup.cfg
This commit does the following:
- Added default setup.cfg (Refer to [CAM Developer's Guide](https://docs.google.com/document/d/1aZoIyR9tz5rCWr2qJKuMTmKp2IzHlFjrCFrpDDHFypM/edit#heading=h.whqqrvn0pw8f) which adds PEP8 strictness.)
- Added pyproject.toml config file which contains isort and black configurations/parameters.
- Added linting to static analysis stage on Jenkins
JIRA: [MT-1063](https://skaafrica.atlassian.net/browse/MT-1063)
> Automate code linting and reject PR if fails.

- .gitignore
- astrokat/simulate.py
- astrokat/test/test_nd_timings.py
- astrokat/test/test_offline_observe.py
- astrokat/test/test_simulate.py
- tox.ini
Improve slew time estimation by taking the mechanical accelerations into account, and combine that with some empirically modelled parameters.
Thanks to @vasaantk for the analysis and reference implementation of the updated slew calculations.
JIRA: [MT-1206](https://skaafrica.atlassian.net/browse/MT-1206)
> Include acceleration in slew time estimation

- astrokat/test/test_obs/image-single-sim.yaml
- astrokat/test/test_obs/raster-scans-sim.yaml
- astrokat/test/test_obs/targets-sim.yaml
- astrokat/utility.py
when yaml loads the file, it converted start_time to date with timezone if the data string has 'Z' in it. Need to remove the timezone, or will get error:
TypeError: can't subtract offset-naive and offset-aware datetimes
> set timezone of start_time parsed by yaml to None

- astrokat/observatory.py
[MT-1257: Timestamp in astrokat during simulate](https://skaafrica.atlassian.net/browse/MT-1257)
Fixing last of the simulation logging timing issue.  Cataglue does not need a date.
> catalogue debuggings have incorrect timing.

- setup.py
matplotlib<3 can't be installed on ubuntu 20.xx. This won't effect simulation and observation.
Just need to make sure users use ubuntu>20 if they want to use plotting utilities of astrokat.
> fix install on ubuntu 20 problem

- astrokat/simulate.py
Fixing simulation error reported by Xinyu
```
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/katsdpopt/observation.py", line 1418, in simulate_ob
verify_result = await verify_obs(script_profile_config, start_date)
File "/usr/local/lib/python3.8/dist-packages/katsdpopt/astrokat_service.py", line 43, in verify_obs
observe_main.main(['--yaml', fp.name])
File "/usr/local/lib/python3.8/dist-packages/astrokat/observe_main.py", line 916, in main
with Telescope(opts) as kat:
File "/usr/local/lib/python3.8/dist-packages/astrokat/observe_main.py", line 327, in __enter__
noisediode.off(self.array)
File "/usr/local/lib/python3.8/dist-packages/astrokat/noisediode.py", line 259, in off
true_timestamp = _switch_on_off_(kat, timestamp)
File …
```
> replace StopIteration with empty return in __iter__ function

- astrokat/observe_main.py
- astrokat/simulate.py
- astrokat/test/test_nd_timings.py
`FBFUSE` / MeerTIME observations had some issues with the astrokat observation script when `FBFUSE` ran commensally in the array with a MeerTIME pulsar observation.
Errors and ideas were discussed during a site integration session and it was noticed that astrokat on the "slew to first target" -- lacks the `fbf.check_provisioning_beams_complete` as implemented in `sessions.capture_start`. This allows the FBF setup of the beams
For astrokat the optimal implementation of this missing requirement was to add an explicit *slew* function to replace the current 0 sec duration track that mimicked the slew.
During this slew to first target (which is expected to be the longest slew in general) the FBF beam check is initiated once the antennas are instructed to POINT to target, this should utilise …
> Slew instead of 0-second track for first target to help FBFUSE

- astrokat/observe_main.py
- astrokat/simulate.py
- astrokat/test/test_nd_timings.py
Reverts ska-sa/astrokat#92
For details see issue #93
As we want to do a new CAM release, we need CAM AQF tests to pass, so reverting the change in the meantime.
> Revert "Slew instead of 0-second track for first target to help FBFUSE"

- astrokat/__init__.py
- astrokat/noisediode.py
- astrokat/observe_main.py
- astrokat/test/test_nd/nd-pattern-plus-off.yaml
Turning off 63 L-band noise diodes on 2021-04-15 took about 3.3 seconds, much longer than the usual 1.0 - 1.5 seconds. This caused the final few KATCP requests to fail and the script to crash.
The culprit is the increased number of S-band digitisers being serviced by the digitiser master controller, so this situation may persist in the near future. For now, increase the lead time from 3.0 to 5.0 seconds.
Do some refactoring of the lead time constant and `max_cycle_len` function. These seem to be used exclusively inside the `noisediode` module within `astrokat`. Please advise if external user scripts expect them at the top level of the package.
Improve the error handling when the lead time is too short. Check if we ran out of time and skip the rest of the noise diodes while reporting the …
> OPS-1899: Increase noise diode lead time and handle errors better

- astrokat/noisediode.py
This PR adds Ludwig's patch in https://github.com/ska-sa/astrokat/pull/99 to the astrokat release branch. This corrects a bug in how the katcp reply from the noisediode request is checked.
> Fix katcp request reply check for noisediode

- tox.ini
This PR does the following:
- Pins the version of `coverage` to a more stable version that supports both Python2 and Python3
Hopefully, this fixes these [build failures](http://ci.camlab.kat.ac.za/job/astrokat-multibranch/job/master/)
> Pin `coverage` to the latest version

- astrokat/test/test_offline_observe.py
- astrokat/utility.py
Remove timezone info from `start_time` after loading from YAML.  If times have a trailing "Z", then the string representations are like 2019-02-11 02:10:47+00:00.  ephem <= 3.7.7.1 was OK to parse that (and ignored the timezone suffix).  Since version 4.0.0.1, the ephem parser is stricter and complains about these times.
This problem wasn't seen in the astrokat unit tests for this repo, but was picked up in the CAM AQF tests.  CAM AQF use katcorelib, instead of the simulated session.  The difference in katcorelib is that the start time is converted via `katpoint.Timestamp`, instead of `astrokat.datetime2timestamp`.
Added a unit test to ensure the conversions between astrokat and katpoint are equivalent, and exercise the ephem converter.
See more details …
> Support pyephem 4.0 time parser

- astrokat/test/test_scans.py
The observation output messages differ between astrokat's [simulate](https://github.com/ska-sa/astrokat/blob/203e5f55797212029cdc87bbbee86f71764f6aa2/astrokat/simulate.py#L231-L233) module and katcorelib's [mkat_session](https://github.com/ska-sa/katcorelib/blob/c4f8e083a8afa26322a099f65d026f08a2255342/katcorelib/mkat_session.py#L1089-L1116) module.  The tests were only considering the messages generated by the simulate module.  Now we also check for messages in the format that katcorelib creates them.
This is to get CAM's AQF test run of astrokat's unit tests to pass:
```
======================================================================
FAIL: Check (az, el) target from (ra, dec) for drift scan
----------------------------------------------------------------------
Traceback (most …
```
> Support katcorelib in drift scan tests

- astrokat/observe_main.py
- astrokat/scans.py
- astrokat/simulate.py
- astrokat/test/test_nd_timings.py
- astrokat/test/test_offline_observe.py
- astrokat/test/test_scans.py
- astrokat/test/test_scans/reference-pointing-scan-test.yaml
- scripts/astrokat-targets.py
We recently added a function that will perform reference pointing scans in katcorelib. In this PR we modify astrokat to enable that same functionality for astrokat observe script.
Tasklog - http://10.8.67.120:8081/tailtask/20221129-0011/progress
Will wait for the right LST to start observation to see outcomes.
JIRA: [MT-3213](https://skaafrica.atlassian.net/browse/MT-3213)
> Implement reference pointing in astrokat

- astrokat/observe_main.py
- astrokat/simulate.py
- astrokat/test/test_nd_timings.py
- astrokat/test/test_offline_observe.py
- astrokat/test/test_scans.py
The function call to `reference_pointing_scan` was placed among the "scans" and led to a confusion in how many tracks of the target during calls `reversescan`. We now move the check if the observation is "reference_pointing" to earlier in our logic.
Reference pointing gives the expected telstateError result - http://10.8.67.104:8081/tailtask/20230206-0001/progress
[MASTER.txt](https://github.com/ska-sa/astrokat/files/10667766/MASTER.txt)
[after_fix.txt](https://github.com/ska-sa/astrokat/files/10667761/after_fix.txt)
JIRA: [MT-3289](https://skaafrica.atlassian.net/browse/MT-3289)
[MT-3289]: https://skaafrica.atlassian.net/browse/MT-3289?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Improve reference pointing functionality

- astrokat/noisediode.py
- astrokat/observe_main.py
As reported in [OPS-2080](https://skaafrica.atlassian.net/browse/OPS-2080), the observation script switches the noisediodes off at the end of observations. There have been issues on site where lost connection to a receptor results in failure to switch the noisediodes off on all other antennas on the array, which reports a failure. Here we attempt to mitigate that by using the current time as the time to reset the noisediode.
We still need to test this, so please take this as a draft PR.
JIRA: [MT-3844](https://skaafrica.atlassian.net/browse/MT-3844)
[OPS-2080]: https://skaafrica.atlassian.net/browse/OPS-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[MT-3844]: https://skaafrica.atlassian.net/browse/MT-3844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
> Issue noisediode deactivation to happen now

- astrokat/noisediode.py
- astrokat/observe_main.py
This PR adds a function to turn off noisediodes using the "now" timestamp. Also, the call to turn off noise diodes is added at the end of the schedule block and removed from the beginning. The action of turning off noisediodes at the beginning of the schedule block is already done by mkat session as part of the standard setup.
This PR adds the work from https://github.com/ska-sa/astrokat/pull/118 to the release branch and addresses the issue reported in [OPS-2080](https://skaafrica.atlassian.net/browse/OPS-2080)
[OPS-2080]: https://skaafrica.atlassian.net/browse/OPS-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add function to turn off noisediodes using the 'now' timestamp

- astrokat/scans.py
- astrokat/test/test_scans.py
This bug was raised in ticket  #120 
Adding an float  to a ephem_date date object returns an float number of days from 1900 plus the float value. 
This when passed to a katpoint target object is interpreted as a unix epoch,  number of seconds from 1970.  
There are two bugs in the code : 
1. First the duration that is added is in seconds but when added to ephem_date is interperated as days. 
2. Second the result which is days is assumed to be unix epoch seconds. 
This is fixed by first converting the ephem_date object to a katpoint.Timestamp object then adding the float number of seconds. Then using  the to_ephem_date method of the katpoint.Timestamp to convert it back.
> Fix Timestamp issue on driftscan

- astrokat/observe_main.py
- astrokat/test/test_scans.py
- astrokat/test/test_scans/reference-pointing-scan-test.yaml
- Obtain scan parameters from `reference_pointing_scan` section in YAML.
- Use target_list `duration` as scan duration instead of duplicating it.
- Add `reference_pointing` section in YAML to adjust the pointing.
Update the unit tests to reflect this.
This addresses ticket SPR1-3072.
> SPR1-3072: Refresh reference pointing YAML API
